import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Clock, Loader2 } from 'lucide-react';
import { ApiError, apiRequest } from '../../lib/api';

type Log = { id: string | number; type?: string; status?: string; work_date?: string; created_at?: string; user?: { full_name?: string; username?: string }; location?: { name?: string } | null };
type Response = { items?: Log[]; data?: Log[] };
const monthValue = new Date().toISOString().slice(0, 7);
const dateBounds = (month: string) => { const [year, value] = month.split('-').map(Number); const last = new Date(Date.UTC(year, value, 0)).getUTCDate(); return { from: `${month}-01`, to: `${month}-${String(last).padStart(2, '0')}` }; };

export default function FinanceAttendancePage() {
  const [month, setMonth] = useState(monthValue); const [logs, setLogs] = useState<Log[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const { from, to } = dateBounds(month); setLoading(true); setError(''); void apiRequest<Response>(`/attendance/logs?limit=200&date_from=${from}&date_to=${to}`).then(response => setLogs(response.items || response.data || [])).catch(err => setError(err instanceof ApiError ? err.message : 'Không tải được dữ liệu chấm công.')).finally(() => setLoading(false)); }, [month]);
  const grouped = useMemo(() => { const map = new Map<string, { name: string; username: string; days: Set<string>; logs: number }>(); logs.filter(log => log.status === 'SUCCESS').forEach(log => { const key = String((log as Log & { user_id?: string | number }).user_id || log.user?.username || log.user?.full_name || 'unknown'); const current = map.get(key) || { name: log.user?.full_name || 'Nhân sự', username: log.user?.username || '—', days: new Set<string>(), logs: 0 }; if (log.work_date) current.days.add(log.work_date); current.logs += 1; map.set(key, current); }); return [...map.values()].sort((a, b) => a.name.localeCompare(b.name)); }, [logs]);
  return <div className="h-full min-h-0 flex flex-col gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-black">Bảng chấm công</h1><p className="text-sm text-muted-foreground">Tổng hợp log GPS thành ngày công theo tháng.</p></div><label className="text-sm font-bold">Tháng <input type="month" value={month} onChange={event => setMonth(event.target.value)} className="ml-2 h-10 rounded-lg border border-border px-3" /></label></div><div className="min-h-0 flex-1 overflow-auto rounded-2xl border border-border bg-white shadow-sm">{loading ? <div className="flex h-60 items-center justify-center text-sm text-muted-foreground"><Loader2 className="mr-2 animate-spin" size={18} />Đang tải...</div> : error ? <div className="p-6 text-sm font-bold text-red-600"><AlertTriangle className="mr-2 inline" size={16} />{error}</div> : <table className="w-full min-w-[620px] text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-muted-foreground"><tr><th className="border-b border-border px-4 py-3">Nhân sự</th><th className="border-b border-border px-4 py-3">Ngày công</th><th className="border-b border-border px-4 py-3">Số log</th><th className="border-b border-border px-4 py-3">Ghi chú</th></tr></thead><tbody>{grouped.map(row => <tr key={row.username} className="border-b border-border"><td className="px-4 py-3"><div className="font-bold">{row.name}</div><div className="text-xs text-muted-foreground">{row.username}</div></td><td className="px-4 py-3 font-bold">{row.days.size}</td><td className="px-4 py-3">{row.logs}</td><td className="px-4 py-3 text-muted-foreground"><Clock className="mr-1 inline" size={14} />Theo log thành công</td></tr>)}</tbody></table>}</div></div>;
}
