import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BadgeDollarSign, Loader2 } from 'lucide-react';
import { ApiError, apiRequest } from '../../lib/api';
import { formatMoney } from '../../lib/formatMoney';

type Staff = { id: string | number; full_name?: string; name?: string; username?: string; monthly_salary?: number | string; is_active?: boolean };
type Log = { user_id?: string | number; user?: { id?: string | number }; work_date?: string; status?: string };
const currentMonth = new Date().toISOString().slice(0, 7);
const bounds = (month: string) => { const [year, value] = month.split('-').map(Number); const last = new Date(Date.UTC(year, value, 0)).getUTCDate(); return { from: `${month}-01`, to: `${month}-${String(last).padStart(2, '0')}` }; };
const list = <T,>(response: T[] | { items?: T[]; data?: T[]; users?: T[] }) => Array.isArray(response) ? response : response.items || response.data || response.users || [];

export default function FinancePayrollPage() {
  const [month, setMonth] = useState(currentMonth); const [staff, setStaff] = useState<Staff[]>([]); const [logs, setLogs] = useState<Log[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const { from, to } = bounds(month); setLoading(true); void Promise.all([apiRequest<Staff[] | { items?: Staff[]; data?: Staff[]; users?: Staff[] }>('/users?limit=100&is_active=true'), apiRequest<{ items?: Log[]; data?: Log[] }>(`/attendance/logs?limit=200&date_from=${from}&date_to=${to}`)]).then(([users, attendance]) => { setStaff(list(users)); setLogs(attendance.items || attendance.data || []); }).catch(err => setError(err instanceof ApiError ? err.message : 'Không tải được dữ liệu tính lương.')).finally(() => setLoading(false)); }, [month]);
  const rows = useMemo(() => { const days = new Map<string, Set<string>>(); logs.filter(log => log.status === 'SUCCESS').forEach(log => { const id = String(log.user_id ?? log.user?.id ?? ''); if (!id || !log.work_date) return; const dates = days.get(id) || new Set<string>(); dates.add(log.work_date); days.set(id, dates); }); return staff.map(user => { const workDays = days.get(String(user.id))?.size || 0; const salary = Number(user.monthly_salary || 0); return { ...user, workDays, salary, estimated: salary * Math.min(workDays / 26, 1) }; }); }, [staff, logs]);
  const total = rows.reduce((sum, row) => sum + row.estimated, 0);
  return <div className="h-full min-h-0 flex flex-col gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-black">Tính lương theo ngày công</h1><p className="text-sm text-muted-foreground">Bảng tạm tính: lương cơ bản × ngày công / 26.</p></div><label className="text-sm font-bold">Tháng <input type="month" value={month} onChange={event => setMonth(event.target.value)} className="ml-2 h-10 rounded-lg border border-border px-3" /></label></div>{!loading && !error && <div className="flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3"><BadgeDollarSign className="text-emerald-600" size={20} /><span className="text-sm font-bold text-emerald-800">Tổng tạm tính: {formatMoney(total)}</span></div>}<div className="min-h-0 flex-1 overflow-auto rounded-2xl border border-border bg-white shadow-sm">{loading ? <div className="flex h-60 items-center justify-center text-sm text-muted-foreground"><Loader2 className="mr-2 animate-spin" size={18} />Đang tính...</div> : error ? <div className="p-6 text-sm font-bold text-red-600"><AlertTriangle className="mr-2 inline" size={16} />{error}</div> : <table className="w-full min-w-[700px] text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-muted-foreground"><tr><th className="border-b border-border px-4 py-3">Nhân sự</th><th className="border-b border-border px-4 py-3">Lương cơ bản</th><th className="border-b border-border px-4 py-3">Ngày công</th><th className="border-b border-border px-4 py-3">Tạm tính</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b border-border"><td className="px-4 py-3"><div className="font-bold">{row.full_name || row.name || '—'}</div><div className="text-xs text-muted-foreground">{row.username}</div></td><td className="px-4 py-3">{formatMoney(row.salary)}</td><td className="px-4 py-3 font-bold">{row.workDays} / 26</td><td className="px-4 py-3 font-bold text-emerald-700">{formatMoney(row.estimated)}</td></tr>)}</tbody></table>}</div></div>;
}
