import { AlertTriangle, BadgeDollarSign, Download, Loader2, Save } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { ApiError, apiRequest } from '../../lib/api';
import { formatAmountInput, formatAmountInputFromNumber, formatMoney, parseAmountInput } from '../../lib/formatMoney';
import type { StaffRecord } from './staffTypes';

interface PayrollRow extends StaffRecord { month: string; work_days: number; overtime_hours: number; base_by_attendance: number; allowance_by_attendance: number; overtime_pay: number; reward_amount: number; advance_amount: number; carry_in: number; gross_salary: number; net_salary: number; carry_out: number; payroll_note?: string | null }
const currentMonth = new Date().toISOString().slice(0, 7);

export default function FinancePayrollPage() {
  const [month, setMonth] = useState(currentMonth);
  const [rows, setRows] = useState<PayrollRow[]>([]);
  const [drafts, setDrafts] = useState<Record<string, { reward: string; note: string }>>({});
  const [loading, setLoading] = useState(true); const [savingId, setSavingId] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await apiRequest<PayrollRow[]>(`/staff-members/payroll/monthly?month=${month}`); setRows(data); setDrafts(Object.fromEntries(data.map((row) => [String(row.id), { reward: formatAmountInputFromNumber(row.reward_amount), note: row.payroll_note || '' }]))); } catch (failure) { setError(failure instanceof ApiError ? failure.message : 'Không tải được bảng lương.'); } finally { setLoading(false); } }, [month]);
  useEffect(() => { void load(); }, [load]);
  const total = useMemo(() => rows.reduce((sum, row) => sum + Number(row.net_salary || 0), 0), [rows]);
  const saveAdjustment = async (row: PayrollRow) => { const id = String(row.id); setSavingId(id); setError(''); try { const draft = drafts[id] || { reward: '', note: '' }; await apiRequest(`/staff-members/payroll/${id}/${month}`, { method: 'PUT', body: { reward_amount: parseAmountInput(draft.reward), note: draft.note.trim() || null } }); await load(); } catch (failure) { setError(failure instanceof ApiError ? failure.message : 'Không lưu được thưởng và ghi chú.'); } finally { setSavingId(''); } };
  const exportExcel = () => { const data = rows.map((row, index) => ({ STT: index + 1, 'Mã NV': row.employee_code, 'Họ tên': row.full_name, 'Bộ phận': row.department_record?.name || row.department || '', 'Bưu cục': row.hub?.code || row.hub?.name || '', 'Lương cơ bản': Number(row.base_salary || 0), 'Ngày công': row.work_days, 'Ngày công chuẩn': Number(row.standard_work_days || 26), 'Lương theo công': Math.round(row.base_by_attendance), 'Phụ cấp theo công': Math.round(row.allowance_by_attendance), 'Tăng ca (giờ)': row.overtime_hours, 'Tiền tăng ca': Math.round(row.overtime_pay), 'Thưởng': Number(row.reward_amount || 0), 'Dư âm tháng trước': Number(row.carry_in || 0), 'Đã ứng': Number(row.advance_amount || 0), 'Thực lĩnh': Math.round(row.net_salary), 'Ghi chú': row.payroll_note || '' })); const sheet = XLSX.utils.json_to_sheet(data); sheet['!cols'] = [6, 14, 24, 18, 14, 16, 12, 16, 18, 18, 14, 16, 14, 18, 14, 16, 30].map((wch) => ({ wch })); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, 'Bảng lương'); XLSX.writeFile(book, `bang-luong-${month}.xlsx`); };
  return <div className="flex h-full min-h-0 flex-col gap-3">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-black">Bảng lương theo ngày công</h1><p className="text-sm text-muted-foreground">(Lương cơ bản + phụ cấp) / ngày công chuẩn × ngày thực tế + tăng ca + thưởng − đã ứng.</p></div><div className="flex gap-2"><button type="button" onClick={exportExcel} disabled={loading || !rows.length} className="inline-flex h-10 items-center gap-2 rounded-lg border border-emerald-300 bg-emerald-50 px-3 text-sm font-bold text-emerald-700 disabled:opacity-50"><Download size={16} />Tải Excel</button><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="h-10 rounded-lg border border-border px-3 font-bold" /></div></div>
    {!loading && !error && <div className="flex items-center gap-3 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3"><BadgeDollarSign className="text-emerald-600" size={20} /><span className="text-sm font-bold text-emerald-800">Tổng lương tạm tính: {formatMoney(total)}</span></div>}
    {error && <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-bold text-red-700"><AlertTriangle size={15} className="mr-2 inline" />{error}</p>}
    <div className="min-h-0 flex-1 overflow-auto rounded-lg border border-border bg-white shadow-sm">{loading ? <div className="flex h-60 items-center justify-center text-sm text-muted-foreground"><Loader2 size={18} className="mr-2 animate-spin" />Đang tính lương...</div> : !rows.length ? <div className="flex h-60 items-center justify-center text-sm text-muted-foreground">Chưa có nhân sự để tính lương.</div> : <PayrollTable rows={rows} drafts={drafts} savingId={savingId} setDrafts={setDrafts} onSave={saveAdjustment} />}</div>
  </div>;
}

function PayrollTable({ rows, drafts, savingId, setDrafts, onSave }: { rows: PayrollRow[]; drafts: Record<string, { reward: string; note: string }>; savingId: string; setDrafts: React.Dispatch<React.SetStateAction<Record<string, { reward: string; note: string }>>>; onSave: (row: PayrollRow) => Promise<void> }) {
  const headers = ['Nhân sự', 'Bộ phận', 'Bưu cục', 'Lương cơ bản', 'Ngày công', 'Lương theo công', 'Phụ cấp theo công', 'Tăng ca', 'Tiền tăng ca', 'Thưởng', 'Dư âm trước', 'Đã ứng', 'Thực lĩnh', 'Ghi chú', ''];
  return <table className="w-full min-w-[1900px] text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-muted-foreground"><tr>{headers.map((label, index) => <th key={`${label}-${index}`} className={`border-b border-border px-3 py-3 ${index >= 3 && index <= 12 ? 'text-right' : ''}`}>{label}</th>)}</tr></thead><tbody>{rows.map((row) => { const id = String(row.id); const draft = drafts[id] || { reward: '', note: '' }; return <tr key={id} className="border-b border-border"><td className="px-3 py-3"><p className="font-extrabold">{row.full_name}</p><p className="text-xs font-bold text-primary">{row.employee_code}</p></td><td className="px-3 py-3">{row.department_record?.name || row.department || '—'}</td><td className="px-3 py-3">{row.hub?.code || row.hub?.name || '—'}</td><td className="px-3 py-3 text-right">{formatMoney(row.base_salary)}</td><td className="px-3 py-3 text-right font-bold">{Number(row.work_days).toLocaleString('vi-VN')} / {Number(row.standard_work_days || 26).toLocaleString('vi-VN')}</td><td className="px-3 py-3 text-right">{formatMoney(row.base_by_attendance)}</td><td className="px-3 py-3 text-right">{formatMoney(row.allowance_by_attendance)}</td><td className="px-3 py-3 text-right">{Number(row.overtime_hours).toLocaleString('vi-VN')} giờ</td><td className="px-3 py-3 text-right">{formatMoney(row.overtime_pay)}</td><td className="px-3 py-2"><input type="text" inputMode="numeric" value={draft.reward} onChange={(event) => setDrafts((current) => ({ ...current, [id]: { ...draft, reward: formatAmountInput(event.target.value) } }))} className="h-9 w-28 rounded-lg border border-border px-2 text-right font-bold" /></td><td className={`px-3 py-3 text-right font-bold ${row.carry_in < 0 ? 'text-red-600' : ''}`}>{formatMoney(row.carry_in)}</td><td className="px-3 py-3 text-right font-bold text-amber-700">{formatMoney(row.advance_amount)}</td><td className={`px-3 py-3 text-right text-base font-black ${row.net_salary < 0 ? 'text-red-600' : 'text-emerald-700'}`}>{formatMoney(row.net_salary)}</td><td className="px-3 py-2"><input value={draft.note} onChange={(event) => setDrafts((current) => ({ ...current, [id]: { ...draft, note: event.target.value } }))} placeholder="Thưởng lễ, ghi chú..." className="h-9 w-52 rounded-lg border border-border px-2" /></td><td className="px-3 py-2"><button type="button" title="Lưu thưởng và ghi chú" disabled={savingId === id} onClick={() => void onSave(row)} className="flex h-9 w-9 items-center justify-center rounded-lg border border-primary/30 text-primary disabled:opacity-50">{savingId === id ? <Loader2 size={15} className="animate-spin" /> : <Save size={15} />}</button></td></tr>; })}</tbody></table>;
}
