export interface FilterOption { value: string; label: string; }
export interface BadgeConfig { label: string; className: string; }
export interface HubSummary { id: string | number; code?: string | null; name?: string | null; }
export interface UserSummary { id: string | number; username?: string | null; name?: string | null; full_name?: string | null; phone?: string | null; }
export interface TripSummary { id?: string | number; trip_code?: string | null; code?: string | null; status?: string | null; start_hub_id?: string | number | null; end_hub_id?: string | number | null; start_hub?: HubSummary | null; end_hub?: HubSummary | null; driver_name?: string | null; driver_phone?: string | null; carrier_label?: string | null; driver?: UserSummary | null; truck?: { license_plate?: string | null; bks?: string | null; phone?: string | null; ten_lai_xe?: string | null; driver?: UserSummary | null } | null; }
export type ManifestDispatchFields = Record<string, string | number | null | undefined>;
export interface ManifestWaybill { id: string | number; waybill_code?: string | null; sender_info?: string | null; receiver_info?: string | null; weight?: number | string | null; length?: number | string | null; width?: number | string | null; height?: number | string | null; volumetric_weight?: number | string | null; payment_type?: string | null; current_state?: string | null; status?: string | null; cost_amount?: number | string | null; origin_hub_id?: string | number | null; dest_hub_id?: string | number | null; dest_hub?: HubSummary | null; package_count?: number | string | null; noi_den?: string | null; receiver_address?: string | null; the_tich_m3?: number | string | null; loading_position?: number | string | null; dispatch_fields?: ManifestDispatchFields | null; }
export interface LoadPlanningManifest { id: string | number; manifest_code?: string | null; code?: string | null; seal_code?: string | null; origin_hub_id?: string | number | null; dest_hub_id?: string | number | null; origin_hub?: HubSummary | null; dest_hub?: HubSummary | null; status?: string | null; waybill_count?: number | string | null; total_waybills?: number | string | null; total_weight?: number | string | null; weight_total?: number | string | null; trip_id?: string | number | null; trip?: TripSummary | null; trips?: TripSummary[]; closed_at?: string | null; created_at?: string | null; closed_by?: UserSummary | null; created_by?: UserSummary | null; waybills?: ManifestWaybill[]; manifest_waybills?: Array<{ waybill_id?: string | number | null; loading_position?: number | string | null; dispatch_fields?: ManifestDispatchFields | null; waybill?: ManifestWaybill | null }>; note?: string | null; }
export interface LoadPlanningFilters { keyword: string; status: string[]; origin_hub_id: string[]; dest_hub_id: string[]; trip_id: string[]; date_from: string; date_to: string; page: number; limit: number; }
export interface ManifestListResponse { data?: LoadPlanningManifest[]; items?: LoadPlanningManifest[]; manifests?: LoadPlanningManifest[]; total?: number; meta?: { total?: number; page?: number; limit?: number }; }
export interface TripListResponse { data?: TripSummary[]; items?: TripSummary[]; trips?: TripSummary[]; total?: number; meta?: { total?: number }; }
export interface AssignTripFormState { trip_id: string; }
export interface ManifestFormState { origin_hub_id: string; dest_hub_id: string; seal_code: string; note: string; }
export interface CloseManifestFormState { seal_code: string; note: string; }
export interface AddWaybillsFormState { keyword: string; selectedIds: string[]; page: number; limit: number; }
export type PrintableManifest = LoadPlanningManifest;
